### ISSUE TITLE
Visual bug with borders in buffs list in case of bottom anchor

### ISSUE THREAD

**Issue by raikuxq** [Uberlicious/UberUI#3]
![image](https://user-images.githubusercontent.com/39119518/201271837-953a31cf-5248-43f0-886e-b003c9f4daa1.png)
![image](https://user-images.githubusercontent.com/39119518/201271894-9ebab2d9-ac51-49d7-83c5-2d120be4641f.png)

**Comment by Uberlicious** [comment]
Will have to look at this one and flip the anchors for that option

**Comment by Uberlicious** [comment]
Fixed in latest release.
