### ISSUE TITLE
Default color of friendly nameplates is almost the same as the warlocks class color.

### ISSUE THREAD

**Issue by raikuxq** [Uberlicious/UberUI#4]
Friendly nameplates class colors disabled:
![image](https://user-images.githubusercontent.com/39119518/201272464-a7442d5b-70fc-4520-bf2b-78d5ff65f06c.png)

Friendly nameplates class colors enabled:
![image](https://user-images.githubusercontent.com/39119518/201272566-85a3af0a-9c47-40cc-be14-616446b79401.png)

Colors difference:
![image](https://user-images.githubusercontent.com/39119518/201273294-9e3493e2-3297-4928-a54b-65f06fa034d1.png)

**Comment by Uberlicious** [comment]
That is stock blizzard color. If nameplate class coloring is off Uber UI does not do any color modifications to the nameplates, it simply turns off the cvar.
