### ISSUE TITLE
Lua errors on Uber UI-10.0.2.8-Beta

### ISSUE THREAD

**Issue by Simprox1** [Uberlicious/UberUI#5]
`23x Interface/AddOns/Uber UI/core/playerframe.lua:43: attempt to index field 'HealthBar' (a nil value)
[string "@Interface/AddOns/Uber UI/core/playerframe.lua"]:43: in function `HealthBarColor'
[string "@Interface/AddOns/Uber UI/options.lua"]:442: in function `SetValue'
[string "@Interface/SharedXML/Settings/Blizzard_SettingControls.lua"]:352: in function <...face/SharedXML/Settings/Blizzard_SettingControls.lua:348>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:143: in function <Interface/SharedXML/CallbackRegistry.lua:142>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
[string "@Interface/SharedXML/Settings/Blizzard_SettingControls.lua"]:301: in function <...face/SharedXML/Settings/Blizzard_SettingControls.lua:300>

Locals:
self = Frame {
 0 = <userdata>
 HealthManaBarTexture = <function> defined @Interface/AddOns/Uber UI/core/playerframe.lua:50
 Color = <function> defined @Interface/AddOns/Uber UI/core/playerframe.lua:23
 HealthBarColor = <function> defined @Interface/AddOns/Uber UI/core/playerframe.lua:37
 ColorTotems = <function> defined @Interface/AddOns/Uber UI/core/playerframe.lua:89
 ColorComboPoints = <function> defined @Interface/AddOns/Uber UI/core/playerframe.lua:116
 PvPIcon = <function> defined @Interface/AddOns/Uber UI/core/playerframe.lua:85
 ColorAlternateMana = <function> defined @Interface/AddOns/Uber UI/core/playerframe.lua:103
 ColorHolyPower = <function> defined @Interface/AddOns/Uber UI/core/playerframe.lua:110
}
playerFrame = Frame {
 0 = <userdata>
 ManaBarMask = MaskTexture {
 }
 ManaBarArea = Frame {
 }
 HealAbsorbBar = Texture {
 }
 StatusTexture = Texture {
 }
 HealthBarArea = Frame {
 }
 OverHealAbsorbGlow = Texture {
 }
 HealthBarMask = MaskTexture {
 }
 HealAbsorbBarRightShadow = Texture {
 }
 HealAbsorbBarLeftShadow = Texture {
 }
 ManaCostPredictionBar = Texture {
 }
 OverAbsorbGlow = Texture {
 }
 TotalAbsorbBar = Texture {
 }
 TotalAbsorbBarOverlay = Texture {
 }
 OtherHealPredictionBar = Texture {
 }
 MyHealPredictionBar = Texture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'HealthBar' (a nil value)"
classcolor = <table> {
 colorStr = "ffffffff"
 b = 1
 g = 1
 GetRGBA = <function> defined @Interface/SharedXML/Color.lua:28
 SetRGB = <function> defined @Interface/SharedXML/Color.lua:43
 GetRGB = <function> defined @Interface/SharedXML/Color.lua:20
 OnLoad = <function> defined @Interface/SharedXML/Color.lua:9
 GenerateHexColorMarkup = <function> defined @Interface/SharedXML/Color.lua:51
 WrapTextInColorCode = <function> defined @Interface/SharedXML/Color.lua:55
 GenerateHexColor = <function> defined @Interface/SharedXML/Color.lua:47
 IsEqualTo = <function> defined @Interface/SharedXML/Color.lua:13
 SetRGBA = <function> defined @Interface/SharedXML/Color.lua:36
 r = 1
 GetRGBAsBytes = <function> defined @Interface/SharedXML/Color.lua:24
 GetRGBAAsBytes = <function> defined @Interface/SharedXML/Color.lua:32
}
`

**Comment by Uberlicious** [comment]
Beta release currently only works for beta. Player frame names are different on live vs beta.
