### ISSUE TITLE
Getting errors since new Version Uber UI-10.0.2.7.1-Release.zip

### ISSUE THREAD

**Issue by w3bprinz** [Uberlicious/UberUI#6]
I've updated UberUI Today to Uber UI-10.0.2.7.1-Release.zip

And know getting errors.

`10x Interface/AddOns/Uber UI/core/actionbars.lua:57: attempt to call method 'Shwo' (a nil value)
[string "@Interface/AddOns/Uber UI/core/actionbars.lua"]:57: in function `modButton'
[string "@Interface/AddOns/Uber UI/core/actionbars.lua"]:62: in function `Color'
[string "@Interface/AddOns/Uber UI/core/actionbars.lua"]:19: in function <Interface/AddOns/Uber UI/core/actionbars.lua:18>

Locals:
button = ActionButton1 {
 CalculateAction = <function> defined @Interface/FrameXML/SecureTemplates.lua:609
 OnLeave = <function> defined @Interface/FrameXML/ActionButton.lua:1193
 FlyoutArrowContainer = Frame {
 }
 NewActionTexture = Texture {
 }
 RightDivider = Frame {
 }
 showButtonArt = true
 UpdateButtonArt = <function> defined @Interface/FrameXML/ActionButton.lua:1227
 QuickKeybindButtonOnLeave = <function> defined @Interface/FrameXML/QuickKeybind.lua:33
 OnDragStart = <function> defined @Interface/FrameXML/ActionButton.lua:1164
 OnReceiveDrag = <function> defined @Interface/FrameXML/ActionButton.lua:1176
 icon = ActionButton1Icon {
 }
 SlotArt = Texture {
 }
 AutoCastable = Texture {
 }
 UpdateState = <function> defined @Interface/FrameXML/ActionButton.lua:497
 UpdatePressAndHoldAction = <function> defined @Interface/FrameXML/ActionButton.lua:340
 HotKey = ActionButton1HotKey {
 }
 HighlightTexture = Texture {
 }
 UpdateOverlayGlow = <function> defined @Interface/FrameXML/ActionButton.lua:682
 GetPagedID = <function> defined @Interface/FrameXML/ActionButton.lua:987
 Update = <function> defined @Interface/FrameXML/ActionButton.lua:378
 IconMask = MaskTexture {
 }
 SpellHighlightAnim = AnimationGroup {
 }
 OnLoad = <function> defined @Interface/FrameXML/ActionButton.lua:279
 PushedTexture = Texture {
 }
 SetTooltip = <function> defined @Interface/FrameXML/ActionButton.lua:896
 Count = ActionButton1Count {
 }
 UpdateUsable = <function> defined @Interface/FrameXML/ActionButton.lua:503
 FlyoutBorderShadow = ActionButton1FlyoutBorderShadow {
 }
 GetShowGrid = <function> defined @Interface/FrameXML/ActionButton.lua:1209
 SetButtonStateBase = <function> defined =[C]:-1
 UpdateHotkeys = <function> defined @Interface/FrameXML/ActionButton.lua:303
 LevelLinkLockIcon = Texture {
 }
 Flash = ActionButton1Flash {
 }
 flashtime = 0
 OnUpdate = <function> defined @Interface/FrameXML/ActionButton.lua:915
 HasAction = <function> defined @Interface/FrameXML/ActionButton.lua:493
 QuickKeybindButtonSetTooltip = <function> defined @Interface/FrameXML/QuickKeybind.lua:52
 SetButtonStateOverride = <function> defined @Interface/FrameXML/ActionButton.lua:1122
 QuickKeybindHighlightTexture = Texture {
 }
 commandName = "ACTIONBUTTON1"
 OnClick = <function> defined @Interface/FrameXML/ActionButton.lua:1127
 index = 1
 feedback_action = 1
 UpdateHighlightMark = <function> defined @Interface/FrameXML/ActionButton.lua:470
 UpdateMouseWheelHandler = <function> defined @Interface/FrameXML/QuickKeybind.lua:86
 QuickKeybindButtonOnMouseWheel = <function> defined @Interface/FrameXML/QuickKeybind.lua:46
 CheckedTexture = Texture {
 }
 flashing = 0
 SetButtonState = <function> defined @Interface/FrameXML/ActionButton.lua:1122
 action = 1
 QuickKeybindButtonOnShow = <function> defined @Interface/FrameXML/QuickKeybind.lua:4
 NormalTexture = ActionButton1NormalTexture {
 }
 QuickKeybindButtonOnClick = <function> defined @Interface/FrameXML/QuickKeybind.lua:16
 UpdateFlash = <function> defined @Interface/FrameXML/ActionButton.lua:991
 QuickKeybindButtonOnUpdate = <function> defined @Interface/FrameXML/QuickKeybind.lua:75
 QuickKeybindButtonOnHide = <function> defined @Interface/FrameXML/QuickKeybind.lua:11
 StartFlash = <function> defined @Interface/FrameXML/ActionButton.lua:1026
 ClearFlash = <function> defined @Interface/FrameXML/ActionButton.lua:1018
 Border = ActionButton1Border {
 }
 BaseActionButtonMixin_OnLoad = <function> defined @Interface/FrameXML/ActionButton.lua:1202
 OnAttributeChanged = <function> defined @Interface/FrameXML/ActionButton.lua:358
 UpdateCount = <function> defined @Interface/FrameXML/ActionButton.lua:525
 BottomDivider = Frame {
 }
 OnEnter = <function> defined @Interface/FrameXML/ActionButton.lua:1182
 UpdateFlyout = <function> defined @Interface/FrameXML/ActionButton.lua:1047
 UpdateAction = <function> defined @Interface/FrameXML/ActionButton.lua:362
 UpdateSpellHighlightMark = <function> defined @Interface/FrameXML/ActionButton.lua:487
 StopFlash = <function> defined @Interface/FrameXML/ActionButton.lua:1032
 SetShowGrid = `

**Comment by w3bprinz** [comment]
```
local function modButton(button)
        local action = button.action;
        if (action == nil) then return end
        local texture = GetActionTexture(action);

        button.NormalTexture:SetVertexColor(dc.r, dc.g, dc.b, dc.a);
        if (uuidb.general.hidehotkeys) then
            button.HotKey:Hide();
        elseif (texture) then
            button.HotKey:Show();
        end

        if (uuidb.general.hidemacros) then
            button.Name:Hide();
        else
            button.Name:Shwo();
        end
    end
```

Thats wrong must be:

```
local function modButton(button)
        local action = button.action;
        if (action == nil) then return end
        local texture = GetActionTexture(action);

        button.NormalTexture:SetVertexColor(dc.r, dc.g, dc.b, dc.a);
        if (uuidb.general.hidehotkeys) then
            button.HotKey:Hide();
        elseif (texture) then
            button.HotKey:Show();
        end

        if (uuidb.general.hidemacros) then
            button.Name:Hide();
        else
            button.Name:Show();
        end
    end
```

There is a spelling error in Line 57 on actionbars.lua

**Comment by Uberlicious** [comment]
Already fixed in latest hotfix an hour ago.

https://github.com/Uberlicious/UberUI/blob/a598ddbf55b505b33219be5b952b12b7bd003caf/changelog.txt#L37-L38
https://www.curseforge.com/wow/addons/uber-ui/files/4086394
